import React, { createContext, useState, useEffect } from 'react';

export const LanguageContext = createContext({ 
  language: 'en', 
  setLanguage: () => {},
  t: () => '' 
});

const translations = {
  en: {
    // Settings
    'account-settings': 'Account Settings',
    'account-information': 'Account Information',
    'username': 'Username',
    'email': 'Email',
    'password-management': 'Password Management',
    'current-password': 'Current Password',
    'new-password': 'New Password',
    'confirm-password': 'Confirm New Password',
    'password-hint': 'Min 8 chars, 1 uppercase, 1 lowercase, 1 number',
    'preferences': 'Preferences',
    'theme': 'Theme',
    'language': 'Language',
    'notifications': 'Notifications',
    'email-notif': 'Email',
    'push-notif': 'Push',
    'sms-notif': 'SMS',
    'privacy': 'Privacy',
    'profile-visibility': 'Profile Visibility',
    'save-changes': 'Save Changes',
    'saving': 'Saving...',
    'success-message': '✅ Settings updated successfully!',
    'delete-account': 'Delete Account',
    'danger-zone': 'Danger Zone',
    'confirm-delete': 'Yes, Delete My Account',
    'cancel': 'Cancel',
    'confirm-delete-message': 'Are you sure? This action cannot be undone.',
    // Navbar
    'home': 'Home',
    'friends': 'Friends',
    'events': 'Events',
    'gallery': 'Gallery',
    'settings': 'Settings',
    'search-users': 'Search users...',
    'messages': 'Messages',
    // Home Page
    'featured-artists': 'Featured Artists',
    'discover-artists': 'Discover amazing artists in our community',
    'view-all': 'View All',
    'top-artists': 'Top Artists - This Week',
    'today': 'Today',
    'this-week': 'This Week',
    'this-month': 'This Month',
    'this-year': 'This Year',
    'all-time': 'All Time',
    'no-featured-artists': 'No featured artists for this time period',
    'try-different-filter': 'Try a different time filter',
    'whats-on-your-mind': "What's on your mind?",
    'add-tags': 'Add tags (comma separated) e.g., painting, digital-art',
    'add-media': 'Add Media',
    'images-videos': 'Images & Videos',
    'share': 'Share',
    // LeftBar
    'following': 'Following',
    'followers': 'Followers',
    // RightBar
    'friends-tab': 'Friends',
    'following-tab': 'Following',
    'followers-tab': 'Followers',
    'no-users-yet': 'No users yet',
    'chat': 'Chat',
    // Profile Page
    'no-bio-available': 'No bio available',
    'edit-bio': 'Edit bio',
    'posts-tab': 'Posts',
    'gallery-tab': 'Gallery',
    'friends-tab-profile': 'Friends',
    'followers-label': 'Followers',
    'following-label': 'Following',
    'posts-label': 'Posts',
    'no-posts-display': 'No posts to display yet',
    's-posts': "'s Posts",
    's-gallery': "'s Gallery",
    's-friends': "'s Friends",
    'all-media': 'All',
    'photos': 'Photos',
    'videos': 'Videos',
    'no-media-found': 'No media found.',
    'no-friends-display': 'No friends to display.',
    'joined': 'Joined',
    'follow-button': 'Follow',
    'following-button': 'Following',
    'friends-button': 'Friends',
    'updating-profile-pic': 'Updating profile picture...',
    'updating-cover-photo': 'Updating cover photo...',
    // Events Page
    'add-event': 'Add Event',
    'recommended-events': 'Recommended Events',
    'all-events': 'All Events',
    'event-title': 'Event Title',
    'event-description': 'Event Description',
    'event-date': 'Event Date',
    'event-location': 'Event Location',
    'event-category': 'Category',
    'event-type': 'Event Type',
    'organization': 'Organization',
    'status': 'Status',
    'upcoming': 'Upcoming',
    'ongoing': 'Ongoing',
    'completed': 'Completed',
    'cancelled': 'Cancelled',
    'search-events': 'Search events...',
    'filter-by-organization': 'Filter by Organization',
    'filter-by-category': 'Filter by Category',
    'no-events-found': 'No events found',
    'event-image': 'Event Image',
    'create-event': 'Create Event',
    'edit-event': 'Edit Event',
    'delete-event': 'Delete Event',
    'register': 'Register',
    'registered': 'Registered',
    'register-event': 'Register for Event',
    'event-requirements': 'Requirements',
    'video-required': 'Video Required',
    'photo-required': 'Photo Required',
    'experience-required': 'Experience Required',
    'max-participants': 'Max Participants',
    'event-price': 'Price',
    'available-seats': 'Available Seats',
    'watch-only': 'Watch Only',
    'audition': 'Audition',
    // My Registrations (Dashboard)
    'my-registrations': 'My Registrations',
    'search-events-registrations': 'Search events or registration id',
    'all-statuses': 'All Statuses',
    'approved': 'Approved',
    'pending': 'Pending',
    'rejected': 'Rejected',
    'newest': 'Newest',
    'oldest': 'Oldest',
    'descending': 'Descending',
    'ascending': 'Ascending',
    'apply': 'Apply',
    'clear': 'Clear',
    'per-page': 'Per page',
    'view-details': 'View Details',
    'view-event': 'View Event',
    'no-registrations': 'You have no registrations yet.',
    'explore-events': 'Explore events',
    'registration-date': 'Registration Date',
    'event-name': 'Event Name',
    'registration-id': 'Registration ID',
    'loading-registrations': 'Loading registrations...',
    // Notifications
    'notifications': 'Notifications',
    'mark-all-as-read': 'Mark all as read',
    'no-notifications-yet': 'No notifications yet',
    'load-more': 'Load more',
    'retry': 'Retry',
    // Chat
    'chats': 'Chats',
    'no-messages': 'No messages',
    'type-message': 'Type a message...',
    'send': 'Send',
    'online': 'Online',
    'offline': 'Offline',
  },
  es: {
    // Settings
    'account-settings': 'Configuración de Cuenta',
    'account-information': 'Información de Cuenta',
    'username': 'Nombre de Usuario',
    'email': 'Correo Electrónico',
    'password-management': 'Gestión de Contraseña',
    'current-password': 'Contraseña Actual',
    'new-password': 'Nueva Contraseña',
    'confirm-password': 'Confirmar Nueva Contraseña',
    'password-hint': 'Mín 8 caracteres, 1 mayúscula, 1 minúscula, 1 número',
    'preferences': 'Preferencias',
    'theme': 'Tema',
    'language': 'Idioma',
    'notifications': 'Notificaciones',
    'email-notif': 'Correo Electrónico',
    'push-notif': 'Push',
    'sms-notif': 'SMS',
    'privacy': 'Privacidad',
    'profile-visibility': 'Visibilidad del Perfil',
    'save-changes': 'Guardar Cambios',
    'saving': 'Guardando...',
    'success-message': '✅ ¡Configuración actualizada con éxito!',
    'delete-account': 'Eliminar Cuenta',
    'danger-zone': 'Zona de Peligro',
    'confirm-delete': 'Sí, Eliminar Mi Cuenta',
    'cancel': 'Cancelar',
    'confirm-delete-message': '¿Estás seguro? Esta acción no se puede deshacer.',
    // Navbar
    'home': 'Inicio',
    'friends': 'Amigos',
    'events': 'Eventos',
    'gallery': 'Galería',
    'settings': 'Configuración',
    'search-users': 'Buscar usuarios...',
    'messages': 'Mensajes',
    // Home Page
    'featured-artists': 'Artistas Destacados',
    'discover-artists': 'Descubre artistas increíbles en nuestra comunidad',
    'view-all': 'Ver Todo',
    'top-artists': 'Artistas Principales - Esta Semana',
    'today': 'Hoy',
    'this-week': 'Esta Semana',
    'this-month': 'Este Mes',
    'this-year': 'Este Año',
    'all-time': 'Todos los Tiempos',
    'no-featured-artists': 'No hay artistas destacados para este período',
    'try-different-filter': 'Intenta con un filtro de tiempo diferente',
    'whats-on-your-mind': '¿Qué hay en tu mente?',
    'add-tags': 'Agregar etiquetas (separadas por comas) ej., pintura, arte-digital',
    'add-media': 'Agregar Medios',
    'images-videos': 'Imágenes y Vídeos',
    'share': 'Compartir',
    // LeftBar
    'following': 'Siguiendo',
    'followers': 'Seguidores',
    // RightBar
    'friends-tab': 'Amigos',
    'following-tab': 'Siguiendo',
    'followers-tab': 'Seguidores',
    'no-users-yet': 'Sin usuarios aún',
    'chat': 'Chat',
    // Profile Page
    'no-bio-available': 'Sin biografía disponible',
    'edit-bio': 'Editar biografía',
    'posts-tab': 'Publicaciones',
    'gallery-tab': 'Galería',
    'friends-tab-profile': 'Amigos',
    'followers-label': 'Seguidores',
    'following-label': 'Siguiendo',
    'posts-label': 'Publicaciones',
    'no-posts-display': 'Sin publicaciones para mostrar aún',
    's-posts': "Publicaciones de",
    's-gallery': "Galería de",
    's-friends': "Amigos de",
    'all-media': 'Todos',
    'photos': 'Fotos',
    'videos': 'Vídeos',
    'no-media-found': 'Sin medios encontrados.',
    'no-friends-display': 'Sin amigos para mostrar.',
    'joined': 'Se unió',
    'follow-button': 'Seguir',
    'following-button': 'Siguiendo',
    'friends-button': 'Amigos',
    'updating-profile-pic': 'Actualizando foto de perfil...',
    'updating-cover-photo': 'Actualizando foto de portada...',
    // Events Page
    'add-event': 'Agregar Evento',
    'recommended-events': 'Eventos Recomendados',
    'all-events': 'Todos los Eventos',
    'event-title': 'Título del Evento',
    'event-description': 'Descripción del Evento',
    'event-date': 'Fecha del Evento',
    'event-location': 'Ubicación del Evento',
    'event-category': 'Categoría',
    'event-type': 'Tipo de Evento',
    'organization': 'Organización',
    'status': 'Estado',
    'upcoming': 'Próxima',
    'ongoing': 'En Curso',
    'completed': 'Completada',
    'cancelled': 'Cancelada',
    'search-events': 'Buscar eventos...',
    'filter-by-organization': 'Filtrar por Organización',
    'filter-by-category': 'Filtrar por Categoría',
    'no-events-found': 'Sin eventos encontrados',
    'event-image': 'Imagen del Evento',
    'create-event': 'Crear Evento',
    'edit-event': 'Editar Evento',
    'delete-event': 'Eliminar Evento',
    'register': 'Registrarse',
    'registered': 'Registrado',
    'register-event': 'Registrarse para el Evento',
    'event-requirements': 'Requisitos',
    'video-required': 'Vídeo Requerido',
    'photo-required': 'Foto Requerida',
    'experience-required': 'Experiencia Requerida',
    'max-participants': 'Máximo de Participantes',
    'event-price': 'Precio',
    'available-seats': 'Asientos Disponibles',
    'watch-only': 'Solo Ver',
    'audition': 'Audición',
    // My Registrations (Dashboard)
    'my-registrations': 'Mis Registros',
    'search-events-registrations': 'Buscar eventos o ID de registro',
    'all-statuses': 'Todos los Estados',
    'approved': 'Aprobado',
    'pending': 'Pendiente',
    'rejected': 'Rechazado',
    'newest': 'Más Reciente',
    'oldest': 'Más Antiguo',
    'descending': 'Descendente',
    'ascending': 'Ascendente',
    'apply': 'Aplicar',
    'clear': 'Limpiar',
    'per-page': 'Por página',
    'view-details': 'Ver Detalles',
    'view-event': 'Ver Evento',
    'no-registrations': 'No tienes registros aún.',
    'explore-events': 'Explorar eventos',
    'registration-date': 'Fecha de Registro',
    'event-name': 'Nombre del Evento',
    'registration-id': 'ID de Registro',
    'loading-registrations': 'Cargando registros...',
    // Notifications
    'notifications': 'Notificaciones',
    'mark-all-as-read': 'Marcar todo como leído',
    'no-notifications-yet': 'Sin notificaciones aún',
    'load-more': 'Cargar más',
    'retry': 'Reintentar',
    // Chat
    'chats': 'Chats',
    'no-messages': 'Sin mensajes',
    'type-message': 'Escribe un mensaje...',
    'send': 'Enviar',
    'online': 'En línea',
    'offline': 'Sin conexión',
  },
  fr: {
    // Settings
    'account-settings': 'Paramètres du Compte',
    'account-information': 'Informations du Compte',
    'username': 'Nom d\'Utilisateur',
    'email': 'Email',
    'password-management': 'Gestion du Mot de Passe',
    'current-password': 'Mot de Passe Actuel',
    'new-password': 'Nouveau Mot de Passe',
    'confirm-password': 'Confirmer le Nouveau Mot de Passe',
    'password-hint': 'Min 8 caractères, 1 majuscule, 1 minuscule, 1 chiffre',
    'preferences': 'Préférences',
    'theme': 'Thème',
    'language': 'Langue',
    'notifications': 'Notifications',
    'email-notif': 'Email',
    'push-notif': 'Push',
    'sms-notif': 'SMS',
    'privacy': 'Confidentialité',
    'profile-visibility': 'Visibilité du Profil',
    'save-changes': 'Enregistrer les Modifications',
    'saving': 'Enregistrement...',
    'success-message': '✅ Paramètres mis à jour avec succès!',
    'delete-account': 'Supprimer le Compte',
    'danger-zone': 'Zone Dangereuse',
    'confirm-delete': 'Oui, Supprimer Mon Compte',
    'cancel': 'Annuler',
    'confirm-delete-message': 'Êtes-vous sûr? Cette action ne peut pas être annulée.',
    // Navbar
    'home': 'Accueil',
    'friends': 'Amis',
    'events': 'Événements',
    'gallery': 'Galerie',
    'settings': 'Paramètres',
    'search-users': 'Rechercher des utilisateurs...',
    'messages': 'Messages',
    // Home Page
    'featured-artists': 'Artistes en Vedette',
    'discover-artists': 'Découvrez des artistes incroyables dans notre communauté',
    'view-all': 'Voir Tous',
    'top-artists': 'Meilleurs Artistes - Cette Semaine',
    'today': 'Aujourd\'hui',
    'this-week': 'Cette Semaine',
    'this-month': 'Ce Mois',
    'this-year': 'Cette Année',
    'all-time': 'Tous les Temps',
    'no-featured-artists': 'Pas d\'artistes en vedette pour cette période',
    'try-different-filter': 'Essayez un filtre de temps différent',
    'whats-on-your-mind': 'À quoi penses-tu?',
    'add-tags': 'Ajouter des étiquettes (séparées par des virgules) ex., peinture, art-numérique',
    'add-media': 'Ajouter des Médias',
    'images-videos': 'Images et Vidéos',
    'share': 'Partager',
    // LeftBar
    'following': 'Suivi',
    'followers': 'Abonnés',
    // RightBar
    'friends-tab': 'Amis',
    'following-tab': 'Suivi',
    'followers-tab': 'Abonnés',
    'no-users-yet': 'Pas d\'utilisateurs pour le moment',
    'chat': 'Chat',
    // Profile Page
    'no-bio-available': 'Pas de biographie disponible',
    'edit-bio': 'Modifier la biographie',
    'posts-tab': 'Publications',
    'gallery-tab': 'Galerie',
    'friends-tab-profile': 'Amis',
    'followers-label': 'Abonnés',
    'following-label': 'Suivi',
    'posts-label': 'Publications',
    'no-posts-display': 'Pas de publications à afficher pour le moment',
    's-posts': "Publications de",
    's-gallery': "Galerie de",
    's-friends': "Amis de",
    'all-media': 'Tous',
    'photos': 'Photos',
    'videos': 'Vidéos',
    'no-media-found': 'Aucun média trouvé.',
    'no-friends-display': 'Pas d\'amis à afficher.',
    'joined': 'Inscrit',
    'follow-button': 'Suivre',
    'following-button': 'Suivi',
    'friends-button': 'Amis',
    'updating-profile-pic': 'Mise à jour de la photo de profil...',
    'updating-cover-photo': 'Mise à jour de la photo de couverture...',
    // Events Page
    'add-event': 'Ajouter un Événement',
    'recommended-events': 'Événements Recommandés',
    'all-events': 'Tous les Événements',
    'event-title': 'Titre de l\'Événement',
    'event-description': 'Description de l\'Événement',
    'event-date': 'Date de l\'Événement',
    'event-location': 'Lieu de l\'Événement',
    'event-category': 'Catégorie',
    'event-type': 'Type d\'Événement',
    'organization': 'Organisation',
    'status': 'Statut',
    'upcoming': 'À Venir',
    'ongoing': 'En Cours',
    'completed': 'Terminé',
    'cancelled': 'Annulé',
    'search-events': 'Rechercher des événements...',
    'filter-by-organization': 'Filtrer par Organisation',
    'filter-by-category': 'Filtrer par Catégorie',
    'no-events-found': 'Aucun événement trouvé',
    'event-image': 'Image de l\'Événement',
    'create-event': 'Créer un Événement',
    'edit-event': 'Modifier l\'Événement',
    'delete-event': 'Supprimer l\'Événement',
    'register': 'S\'inscrire',
    'registered': 'Inscrit',
    'register-event': 'S\'inscrire à l\'Événement',
    'event-requirements': 'Exigences',
    'video-required': 'Vidéo Requise',
    'photo-required': 'Photo Requise',
    'experience-required': 'Expérience Requise',
    'max-participants': 'Nombre Maximum de Participants',
    'event-price': 'Prix',
    'available-seats': 'Sièges Disponibles',
    'watch-only': 'Regarder Uniquement',
    'audition': 'Audition',
    // My Registrations (Dashboard)
    'my-registrations': 'Mes Inscriptions',
    'search-events-registrations': 'Rechercher des événements ou ID d\'inscription',
    'all-statuses': 'Tous les Statuts',
    'approved': 'Approuvé',
    'pending': 'En Attente',
    'rejected': 'Rejeté',
    'newest': 'Plus Récent',
    'oldest': 'Plus Ancien',
    'descending': 'Décroissant',
    'ascending': 'Croissant',
    'apply': 'Appliquer',
    'clear': 'Effacer',
    'per-page': 'Par page',
    'view-details': 'Voir les Détails',
    'view-event': 'Voir l\'Événement',
    'no-registrations': 'Vous n\'avez pas d\'inscriptions pour le moment.',
    'explore-events': 'Explorez les événements',
    'registration-date': 'Date d\'Inscription',
    'event-name': 'Nom de l\'Événement',
    'registration-id': 'ID d\'Inscription',
    'loading-registrations': 'Chargement des inscriptions...',
    // Notifications
    'notifications': 'Notifications',
    'mark-all-as-read': 'Marquer tout comme lu',
    'no-notifications-yet': 'Pas encore de notifications',
    'load-more': 'Charger plus',
    'retry': 'Réessayer',
    // Chat
    'chats': 'Chats',
    'no-messages': 'Pas de messages',
    'type-message': 'Tapez un message...',
    'send': 'Envoyer',
    'online': 'En ligne',
    'offline': 'Hors ligne',
  },
  tl: {
    // Settings
    'account-settings': 'Mga Setting ng Account',
    'account-information': 'Impormasyon ng Account',
    'username': 'Username',
    'email': 'Email',
    'password-management': 'Pamamahala ng Password',
    'current-password': 'Kasalukuyang Password',
    'new-password': 'Bagong Password',
    'confirm-password': 'Kumpirmahin ang Bagong Password',
    'password-hint': 'Kailan-kailan 8 character, 1 uppercase, 1 lowercase, 1 numero',
    'preferences': 'Mga Kagustuhan',
    'theme': 'Tema',
    'language': 'Wika',
    'notifications': 'Mga Notipikasyon',
    'email-notif': 'Email',
    'push-notif': 'Push',
    'sms-notif': 'SMS',
    'privacy': 'Privacy',
    'profile-visibility': 'Visibility ng Profile',
    'save-changes': 'I-save ang Mga Pagbabago',
    'saving': 'Isinasave...',
    'success-message': '✅ Matagumpay na nag-update ng setting!',
    'delete-account': 'Tanggalin ang Account',
    'danger-zone': 'Danger Zone',
    'confirm-delete': 'Oo, Tanggalin ang Aking Account',
    'cancel': 'Kanselahin',
    'confirm-delete-message': 'Sigurado ka na? Ang aksyong ito ay hindi maaaring bawiin.',
    // Navbar
    'home': 'Home',
    'friends': 'Mga Kaibigan',
    'events': 'Mga Evento',
    'gallery': 'Galeria',
    'settings': 'Setting',
    'search-users': 'Maghanap ng mga gumagamit...',
    'messages': 'Mga Mensahe',
    // Home Page
    'featured-artists': 'Featured Artists',
    'discover-artists': 'Tuklasin ang mga kahanga-hangang artist sa aming komunidad',
    'view-all': 'Tingnan ang Lahat',
    'top-artists': 'Top Artists - Ngayong Linggo',
    'today': 'Ngayon',
    'this-week': 'Ngayong Linggo',
    'this-month': 'Ngayong Buwan',
    'this-year': 'Ngayong Taon',
    'all-time': 'Lahat ng Panahon',
    'no-featured-artists': 'Walang featured artists para sa panahong ito',
    'try-different-filter': 'Subukan ang ibang time filter',
    'whats-on-your-mind': 'Ano ang nasa iyong isip?',
    'add-tags': 'Magdagdag ng mga tag (comma separated) e.g., painting, digital-art',
    'add-media': 'Magdagdag ng Media',
    'images-videos': 'Mga Larawan at Video',
    'share': 'Ibahagi',
    // LeftBar
    'following': 'Sumusunod',
    'followers': 'Mga Tagasunod',
    // RightBar
    'friends-tab': 'Mga Kaibigan',
    'following-tab': 'Sumusunod',
    'followers-tab': 'Mga Tagasunod',
    'no-users-yet': 'Walang mga gumagamit pa',
    'chat': 'Chat',
    // Profile Page
    'no-bio-available': 'Walang biography na available',
    'edit-bio': 'Baguhin ang biography',
    'posts-tab': 'Mga Post',
    'gallery-tab': 'Galeria',
    'friends-tab-profile': 'Mga Kaibigan',
    'followers-label': 'Mga Tagasunod',
    'following-label': 'Sumusunod',
    'posts-label': 'Mga Post',
    'no-posts-display': 'Walang mga post na ipapakita pa',
    's-posts': "Mga Post ng",
    's-gallery': "Galeria ng",
    's-friends': "Mga Kaibigan ng",
    'all-media': 'Lahat',
    'photos': 'Mga Larawan',
    'videos': 'Mga Video',
    'no-media-found': 'Walang media na nahanap.',
    'no-friends-display': 'Walang mga kaibigan na ipapakita.',
    'joined': 'Sumali',
    'follow-button': 'Sundan',
    'following-button': 'Sumusunod',
    'friends-button': 'Mga Kaibigan',
    'updating-profile-pic': 'Ina-update ang profile picture...',
    'updating-cover-photo': 'Ina-update ang cover photo...',
    // Events Page
    'add-event': 'Magdagdag ng Evento',
    'recommended-events': 'Mga Inirekomendang Evento',
    'all-events': 'Lahat ng Mga Evento',
    'event-title': 'Pamagat ng Evento',
    'event-description': 'Deskripsyon ng Evento',
    'event-date': 'Petsa ng Evento',
    'event-location': 'Lokasyon ng Evento',
    'event-category': 'Kategorya',
    'event-type': 'Uri ng Evento',
    'organization': 'Organisasyon',
    'status': 'Status',
    'upcoming': 'Paparating',
    'ongoing': 'Kasalukuyan',
    'completed': 'Tapos',
    'cancelled': 'Kinansela',
    'search-events': 'Maghanap ng mga evento...',
    'filter-by-organization': 'I-filter ayon sa Organisasyon',
    'filter-by-category': 'I-filter ayon sa Kategorya',
    'no-events-found': 'Walang mga evento na nahanap',
    'event-image': 'Larawan ng Evento',
    'create-event': 'Lumikha ng Evento',
    'edit-event': 'Baguhin ang Evento',
    'delete-event': 'Tanggalin ang Evento',
    'register': 'Mag-register',
    'registered': 'Naka-register',
    'register-event': 'Mag-register para sa Evento',
    'event-requirements': 'Mga Pangangailangan',
    'video-required': 'Video na Kinakailangan',
    'photo-required': 'Larawan na Kinakailangan',
    'experience-required': 'Karanasan na Kinakailangan',
    'max-participants': 'Pinakamataas na Participants',
    'event-price': 'Presyo',
    'available-seats': 'Available na Seats',
    'watch-only': 'Tuklasin Lamang',
    'audition': 'Audisyon',
    // My Registrations (Dashboard)
    'my-registrations': 'Ang Aking Mga Rehistro',
    'search-events-registrations': 'Maghanap ng mga evento o registration id',
    'all-statuses': 'Lahat ng Mga Status',
    'approved': 'Aprubado',
    'pending': 'Naghihintay',
    'rejected': 'Tinanggihan',
    'newest': 'Pinakabago',
    'oldest': 'Pinakaluma',
    'descending': 'Bumababa',
    'ascending': 'Umakyat',
    'apply': 'Ilapat',
    'clear': 'Tanggalin',
    'per-page': 'Bawat pahina',
    'view-details': 'Tingnan ang Detalye',
    'view-event': 'Tingnan ang Evento',
    'no-registrations': 'Wala kang mga rehistro pa.',
    'explore-events': 'Tuklasin ang mga evento',
    'registration-date': 'Petsa ng Rehistro',
    'event-name': 'Pangalan ng Evento',
    'registration-id': 'ID ng Rehistro',
    'loading-registrations': 'Kumukuha ng mga rehistro...',
    // Notifications
    'notifications': 'Mga Notipikasyon',
    'mark-all-as-read': 'Markahan ang lahat bilang nabasa',
    'no-notifications-yet': 'Walang notipikasyon pa',
    'load-more': 'Magkarga pa',
    'retry': 'Subukan ulit',
    // Chat
    'chats': 'Mga Chat',
    'no-messages': 'Walang mensahe',
    'type-message': 'Magsulat ng mensahe...',
    'send': 'Ipadala',
    'online': 'Online',
    'offline': 'Offline',
  },
};

export const LanguageContextProvider = ({ children }) => {
  const readInitial = () => {
    try {
      const currentUserJson = localStorage.getItem('currentUser') || localStorage.getItem('adminUser');
      if (currentUserJson) {
        const user = JSON.parse(currentUserJson);
        const lang = user?.customization?.language || user?.language;
        if (lang && translations[lang]) return lang;
      }
    } catch (e) { /* ignore */ }

    try {
      const stored = localStorage.getItem('language');
      if (stored && translations[stored]) return stored;
    } catch (e) { /* ignore */ }

    return 'en';
  };

  const [language, setLanguageState] = useState(readInitial);

  const setLanguage = (lang) => {
    if (translations[lang]) {
      setLanguageState(lang);
      try {
        localStorage.setItem('language', lang);
        const currentUserJson = localStorage.getItem('currentUser') || localStorage.getItem('adminUser');
        if (currentUserJson) {
          try {
            const user = JSON.parse(currentUserJson);
            user.customization = user.customization || {};
            user.customization.language = lang;
            const key = localStorage.getItem('currentUser') ? 'currentUser' : 'adminUser';
            localStorage.setItem(key, JSON.stringify(user));
          } catch (e) { /* ignore */ }
        }
      } catch (e) { /* ignore */ }
      
      // Trigger a custom event so other components know language changed
      if (typeof window !== 'undefined') {
        window.dispatchEvent(new CustomEvent('languageChanged', { detail: { language: lang } }));
      }
    }
  };

  const t = (key) => {
    return translations[language]?.[key] || translations['en']?.[key] || key;
  };

  return (
    <LanguageContext.Provider value={{ language, setLanguage, t }}>
      {children}
    </LanguageContext.Provider>
  );
};
